server:
  port: 8084

spring:
  application:
    name: ScheduleServiceApplication
  data:
    mongodb:
      username: admin
      database: fueldb
      port: 27017
      host: localhost
  kafka:
    consumer:
      group-id: groupId
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

order:
  topic:
    name: order-topic

schedule:
  topic:
    name: schedules-topic

auto:
  create:
    topics:
      enable: true